language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=Django==1.8
  - DJANGO_VERSION=Django==1.9

# command to install dependencies
install:
  - pip install $DJANGO_VERSION
  - pip install -r test-requirements.txt

# command to run tests

script:
  - python runtests.py
